# Site settings
title: FRIENDS
tagline: I'll be there for you
description: All FRIENDS episodes will be listed here.
header-img: img/home1.jpg
email: friends@ibtfu.com
copyright_name: FRIENDS, All Rights Reserved
#description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://www.ibtfu.com"
#url: "http://localhost:4000"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: :categories/:title
#paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-admin]
